name: Release Drafter

on:
  workflow_dispatch:
  # Disabled until .github/cliff.toml exists.

permissions:
  contents: write

jobs:
  update_release_draft:
    name: Update Release Draft
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate a tag
        id: git-cliff-tag
        uses: orhun/git-cliff-action@v4
        with:
          config: ./.github/cliff.toml
          args: --bumped-version

      - name: Generate a changelog
        id: git-cliff-changelog
        uses: orhun/git-cliff-action@v4
        with:
          config: ./.github/cliff.toml
          args: --bump --unreleased

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.git-cliff-tag.outputs.content }}
          name: ${{ steps.git-cliff-tag.outputs.content }} 🌈
          body: ${{ steps.git-cliff-changelog.outputs.content }}
          draft: true
